//Product
export const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT'
export const ADD_NEW_PRODUCT = 'ADD_NEW_PRODUCT'
export const DELETE_A_PRODUCT_FOREVER = 'DELETE_A_PRODUCT_FOREVER'
export const EDIT_PRODUCT = 'EDIT_PRODUCT'
//Customer
export const GET_ALL_CUSTOMER = 'GET_ALL_CUSTOMER'
export const ADD_NEW_CUSTOMER = 'ADD_NEW_CUSTOMER'
export const DELETE_A_CUSTOMER_FOREVER = 'DELETE_A_CUSTOMER_FOREVER'
export const EDIT_CUSTOMER = 'EDIT_CUSTOMER'
//alert
export const SHOW_AN_ALERT = 'SHOW_AN_ALERT'
//Speech
export const LOAD_TRANSCRIPT = 'LOAD_TRANSCRIPT'
export const RESET_TRANSCRIPT = 'RESET_TRANSCRIPT'
//keyword
export const ADD_SECONDKEY = 'ADD_SECONDKEY'
export const ADD_KEYWORD = 'ADD_KEYWORD'
export const SEARCH_BY_KEYWORDS = 'SEARCH_BY_KEYWORDS'
export const DELETE_KEYWORD = 'DELETE_KEYWORD'
export const GET_KEYWORDS_OF_PRODUCT = 'GET_KEYWORDS_OF_PRODUCT'