export const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT'
export const ADD_NEW_PRODUCT = 'ADD_NEW_PRODUCT'
export const DELETE_A_PRODUCT_FOREVER = 'DELETE_A_PRODUCT_FOREVER'
export const EDIT_PRODUCT = 'EDIT_PRODUCT'